language: python

addons:
  apt:
    packages:
    - php5-cli

python:
  - 3.4
  - 3.5

before_install:
  - "curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar"

script: 
  - "cd tests && python -m unittest discover;"
